markdown: kramdown
exclude: ["Gemfile"]
url: https://variationsguide.typenetwork.com
title: Font Bureau OpenType 1.8 Variations Axes Proposals
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
